<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE config-description [
<!ELEMENT config-description  (key*)>
<!ELEMENT key                 (description?, (class | enum | text))>
<!ATTLIST key
   name   CDATA #REQUIRED
   global CDATA #IMPLIED
 >

<!ELEMENT description         (#PCDATA)>
<!ELEMENT class               (EMPTY)>
<!ATTLIST class
  instanceof CDATA #REQUIRED
 >

<!ELEMENT enum               (text)*>
<!ELEMENT text               (#PCDATA)>
 ]>
<config-description>
    <key name="org.jfree.report.ConfigStore" global="true">
        <description>Selects which implementation is responsible for storing configuration information.</description>
        <class instanceof="org.jfree.report.modules.misc.configstore.base.ConfigStorage"/>
    </key>
    <key name="org.jfree.report.LogLevel" global="true">
        <description>The minimum loglevel that is logged.</description>
        <enum>
            <text>Debug</text>
            <text>Info</text>
            <text>Warn</text>
            <text>Error</text>
        </enum>
    </key>
    <key name="org.jfree.report.LogTarget" global="true">
        <description>Selects which implementation is responsible for logging.</description>
        <class instanceof="org.jfree.util.LogTarget"/>
    </key>
    <key name="org.jfree.report.NoDefaultDebug" global="true">
        <description>Defines, whether the debugging system should be disabled by default. This option will surpress all output, no single line of debug information will be printed. If you want to remove System.out-debugging on the server side, try to switch to a Log4J-LogTarget instead.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.PrintOperationComment" global="true">
        <description>Defines, whether the page layouter prints a massive amount of debug messages. This is for debugging only, you wouldn't activate this in a production system.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.StrictErrorHandling" global="true">
        <description>Defines a stricter error handling, if set to true, then all errors that occur during the report processing will cause the report processing to fail. It is safe to set this to true, as valid reports never throw exceptions.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.WarnInvalidColumns" global="true">
        <description>Should the datarow print warning on invalid columns? Invalid column requests always return null. If set to true, an additional logging entry is added.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.ext.modules.barcode.base.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.ext.modules.barcode.io.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.ext.modules.java14config.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.ext.modules.java14log.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.ext.modules.java14print.Enable" global="true">
        <description>Defines, whether to enable the Java.1.4 style printing plugin. At the moment, this only usses the default dialogs, and you should not see any difference to the AWT engine.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.ext.modules.java14print.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.ext.modules.java14print.Order" global="false">
        <description>Defines the export plugin order in the preview dialogs.</description>
        <text/>
    </key>
    <key name="org.jfree.report.ext.modules.jfreechart.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.ext.modules.log4jlog.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.layout.fontrenderer.IsBuggyFRC" global="true">
        <description>This is a override setting. Some Graphics2D implementations have problems with the font positioning. I don't know a way to resolve that bug, try setting this property to &quot;true&quot; to resolve wrong/buggy string draw results.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.layout.fontrenderer.UseAliasing" global="true">
        <description>Enable aliasing for Graphics2D. This may result is textlayout errors on some systems. If your text is not correctly aligned, disable this property.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.base.EncodingsAvailable" global="true">
        <description>The property that defines which encodings are available in the export dialogs. This property defaults to &quot;all&quot; and can be set to  either &quot;all&quot;, &quot;none&quot; or &quot;file&quot;.

If the property is set to &quot;file&quot;, then the list of available properties is read from the file defined in the property &quot;org.jfree.report.encodings.file&quot;.</description>
        <enum>
            <text>all</text>
            <text>file</text>
            <text>none</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.base.EncodingsFile" global="true">
        <description>Defines the name of the properties file used to define the available encodings.

The property points to a resources in the classpath, not to a real file!</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.gui.base.LargeIcons" global="false">
        <description>Defines, whether the toolbar will contain large icons. This is enabled by default.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.base.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.gui.base.SwingDialogTranslation" global="false">
        <description>Defines, whether we should translate the standard swing dialogs.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.base.ToolbarFloatable" global="false">
        <description>Defines, whether the toolbar will be floatable. This is not enabled by default.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.config.EditorFont" global="true">
        <description>The font used to display monospaced text in the text areas</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.gui.config.EditorFontSize" global="true">
        <description>The font size used to display monospaced text.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.gui.config.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.gui.converter.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.gui.csv.Enable" global="false">
        <description>Set to false to disable the CSV export using the preview dialog. This will not prevent anyone from calling the dialog's methods manually, but the export plugin will not be visible by default.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.csv.Encoding" global="false">
        <description>Selected default encoding for the csv export dialog.
This properties does not affect the CSV export directly, it is used to configure the used writer when writing. 

If not defined here, it will default to the platform specific encoding.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.gui.csv.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.gui.csv.Order" global="true">
        <description>Defines the export plugin order in the preview dialogs.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.gui.html.Enable" global="false">
        <description>Set to false to disable the Html export using the preview dialog. This will not prevent anyone from calling the dialog's methods manually, but the export plugin will not be visible by default.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.html.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.gui.html.Order" global="true">
        <description>Defines the export plugin order in the preview dialogs.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.gui.pdf.Enable" global="false">
        <description>Set to false to disable the PDF export using the preview dialog. This will not prevent anyone from calling the dialog's methods manually, but the export plugin will not be visible by default.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.pdf.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.gui.pdf.Order" global="true">
        <description>Defines the export plugin order in the preview dialogs.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.gui.plaintext.Enable" global="false">
        <description>Set to false to disable the PlainText export using the preview dialog. This will not prevent anyone from calling the dialog's methods manually, but the export plugin will not be visible by default.
</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.plaintext.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.gui.plaintext.Order" global="true">
        <description>Defines the export plugin order in the preview dialogs.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.gui.print.Enable" global="false">
        <description>Set to false to disable the PlainText export using the preview dialog. This will not prevent anyone from calling the dialog's methods manually, but the export plugin will not be visible by default.
</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.print.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.gui.print.Order" global="true">
        <description>Defines the export plugin order in the preview dialogs.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.gui.print.pagesetup.Enable" global="false">
        <description>Set to false to disable the PageSetup dialog using the preview dialog. This will not prevent anyone from calling the dialog's methods manually, but the export plugin will not be visible by default.
</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.print.pagesetup.Order" global="true">
        <description>Defines the export plugin order in the preview dialogs.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.gui.xls.Enable" global="false">
        <description>Set to false to disable the Excel export using the preview dialog. This will not prevent anyone from calling the dialog's methods manually, but the export plugin will not be visible by default.
</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.gui.xls.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.gui.xls.Order" global="true">
        <description>Defines the export plugin order in the preview dialogs.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.misc.beanshell.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.misc.configstore.base.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.misc.configstore.filesystem.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.misc.configstore.filesystem.SystemTargetDir" global="true">
        <description>Defines the directory, where the system settings will be stored. If the directory starts with an '~/', the given directory will be considered relative to the users home directory.
</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.misc.configstore.filesystem.UserTargetDir" global="true">
        <description>Defines the directory, where the user settings will be stored. If the directory starts with an '~/', the given directory will be considered relative to the users home directory.
</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.misc.logging.base.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.misc.referencedoc.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.misc.tablemodel.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.misc.tablemodel.TableFactoryMode" global="true">
        <description>The tablemodel factory mode for the ResultSetTableModelFactory if set to &quot;simple&quot; the factory will always return a DefaultTableModel.
</description>
        <enum>
            <text>simple</text>
            <text>auto</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.csv.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.output.csv.Separator" global="false">
        <description>Defines the column separator, defaults to comma.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.csv.WriteDatarowNames" global="false">
        <description>Defines whether to write the column names of the datarow into the first row.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.pageable.base.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.output.pageable.graphics.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.AllowAssembly" global="false">
        <description>Defines, whether the PDF Security setting allows reassmebly of the document by default.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.AllowCopy" global="false">
        <description>Defines, whether the PDF Security setting allows copying of the document's contents by default.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.AllowDegradedPrinting" global="false">
        <description>Defines, whether the PDF Security setting allows low quality printing of the document's contents by default.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.AllowFillIn" global="false">
        <description>Defines, whether the PDF Security setting allows the fill-in of document forms (inputfields etc).</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.AllowModifyAnnotations" global="false">
        <description>Defines, whether the PDF Security setting allows document annotations by default.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.AllowModifyContents" global="false">
        <description>Defines, whether the PDF Security setting allows modifying of the document by default.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.AllowPrinting" global="false">
        <description>Defines, whether the PDF Security setting allows printing of the document's contents by default.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.AllowScreenReaders" global="false">
        <description>Defines, whether the PDF Security setting allows access for screenreaders by default. Although this could make it easier to grab the contents your PDF document, enabling this property will allow blind people to access your content. It is usually a good idea to always enable this property.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.Author" global="false">
        <description>The author string of the document.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.EmbedFonts" global="false">
        <description>Defines whether to embed fonts in the generated PDF. This will result in larger PDF files, but makes sure that all characters are displayed properly.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.Encoding" global="false">
        <description>The default font-encoding for the OutputTarget.
Can be changed with PDFOutputTarget.setFontEncoding for the specific instance if needed.

The encoding can also be defined on a per-element level.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.Encryption" global="false">
        <description>Defines whether the PDF file should be encrypted by default. Set this to &quot;none&quot; &quot;40bit&quot; or &quot;128bit&quot;. 

Access restrictions have no effect if the document
is not encrypted, and not all security settings are active on 40-Bit encryption.</description>
        <enum>
            <text>none</text>
            <text>40bit</text>
            <text>128bit</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.OwnerPassword" global="false">
        <description>Defines the OwnerPassword for the PDF document. The owner has all perfmissions on the document and will be able to change the security settings.

Warning: Specifying passwords in the property file can introduce a security risk. Do not use these settings on the client side or in unprotected (world-readable) server environments. In these cases use other means of defining the password.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.Title" global="false">
        <description>The title of the document.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.pageable.pdf.UserPassword" global="false">
        <description>The default user password for the document. Users are able to access the document within the defined security restrictions.

Warning: Specifying passwords in the property file can introduce a security risk. Do not use these settings on the client side or in unprotected (world-readable) server environments. In these cases use other means of defining the password.
</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.pageable.plaintext.CharsPerInch" global="false">
        <description>Defines the printer font. Valid values are 10, 12, 15, 17 or 20</description>
        <enum>
            <text>10</text>
            <text>12</text>
            <text>15</text>
            <text>17</text>
            <text>20</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.plaintext.Encoding" global="false">
        <description>This property defaults to the current platform encoding, but should
be adjusted when using one of the printer specifc command sets, as these command sets don't support all encodings.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.pageable.plaintext.LinesPerInch" global="false">
        <description>Defines the printer font. Valid values are 6 or 10</description>
        <enum>
            <text>6</text>
            <text>10</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.pageable.plaintext.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.output.support.itext.AutoInit" global="true">
        <description>Defines, whether and how to register the fonts installed on that system. This will search the installed fonts on well-known locations based on the detected system environment.

Lazy font registration will defer the registration process until the font factory is first used. If the registration is defined to happen on init, the fonts will be registered as soon as the module get active for the first time.

The automatic registration can be disabled by setting this configuration entry to &quot;never&quot;. You will have to register the fonts manually before you start the output, or TrueType fonts will not be available. 

Valid values are &quot;onInit&quot;, &quot;never&quot; or &quot;lazy&quot;.</description>
        <enum>
            <text>onInit</text>
            <text>never</text>
            <text>lazy</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.support.itext.Encoding" global="true">
        <description>Defines the encoding to be used during the font initialisation. If not defined, then the plattform default encoding will be used.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.support.itext.GCAfterRegister" global="true">
        <description>Defines, whether to run the garbage collector after the fonts have been registered. </description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.support.itext.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.output.table.base.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.output.table.base.StrictLayout" global="true">
        <description>Defines whether a stricter, but more accurate layout algorithm should be applied. Setting this property to false will greatly reduce the table complexity.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.table.csv.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.output.table.csv.Separator" global="false">
        <description>Defines the default separator, that should be used for the output.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.table.html.Author" global="false">
        <description>Defines a author for generated HTML documents.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.table.html.BodyFragment" global="false">
        <description>Defines whether to define a body fragment only. This removes the header and body tags and makes it easy to include the generated content in own pages.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.table.html.Encoding" global="false">
        <description>Defines the document encoding. If undefined, it defaults to the platforms default encoding.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.table.html.GenerateXHTML" global="false">
        <description>Defines whether to generate XHTML1.0 or HTML4.0 content.</description>
        <enum>
            <text>true</text>
            <text>false</text>
        </enum>
    </key>
    <key name="org.jfree.report.modules.output.table.html.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>
        <class instanceof="org.jfree.report.modules.Module"/>
    </key>
    <key name="org.jfree.report.modules.output.table.html.Title" global="false">
        <description>Defines the default title for generated HTML documents.</description>
        <text/>
    </key>
    <key name="org.jfree.report.modules.output.table.rtf.Module" global="true">
        <description>A module definition. Please do not edit this entry.</description>